---
git_install_from_source: true
git_version: "2.17.0"
git_install_from_source_force_update: true
pip_install_packages:
  - botocore
  - boto3
  - toml
apache_enablerepo: "epel"
apache_packages_state: "latest"
apache_vhosts:
  - servername: "api.dev.vm"
    documentroot: "/home/vagrant/code/fotuapi/public"
    extra_parameters: |
      SetEnv APP_DEBUG 1
      SetEnv APP_ENV dev
      SetEnv DB_HOST localhost
      SetEnv DB_PORT 3306
      SetEnv DB_USER root
      SetEnv DB_PASSWORD root
      ErrorLog logs/fotuapi-error.log
      CustomLog logs/fotuapi-access.log combined
php_version: "7.2"
php_enablerepo: "remi-php72,epel"
php_packages_state: "latest"
php_packages_extra:
  - "php-mysql"
php_pecl_extensions:
  - "redis"
composer_keep_updated: true
redis_enablerepo: "epel"
aerospike_version: "4.0.0.4"
aerospike_tools_version: "3.15.3.2"
aerospike_namespaces:
  - name: fotubox
