---
- name: geerlingguy.git
  version: 2.0.2
- name: geerlingguy.ntp
  version: 1.5.3
- name: geerlingguy.repo-epel
  version: 1.2.2
- name: geerlingguy.repo-remi
  version: 1.2.0
- name: geerlingguy.pip
  version: 1.2.0
- name: geerlingguy.apache
  version: 2.1.1
- name: geerlingguy.mysql
  version: 2.8.3
- name: geerlingguy.php-versions
  version: 2.0.0
- name: geerlingguy.php
  version: 3.5.2
- name: geerlingguy.php-pecl
  version: 1.4.0
- name: geerlingguy.php-xdebug
  version: 2.5.0
- name: geerlingguy.blackfire
  version: 1.0.0
- name: geerlingguy.composer
  version: 1.6.1
- name: geerlingguy.redis
  version: 1.5.1
- name: mplachter.aerospike
  version: 1.1.0
